[package]
name = "sdplugin_manifest"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.108"
test-case = "3.2.1"
